import type { Bundle } from "@epistemic-git/protocol";
import lhcJson from "../../../artifacts/lhc.json";
import eggsJson from "../../../artifacts/eggs.json";
import covidJson from "../../../artifacts/covid.json";
import lhcAddendumJson from "../../../artifacts/lhc-addendum.json";

/**
 * Committed bundles imported directly so the explorer works offline with no API key. Analysis runs
 * on these plain objects in the browser; we never import protocol at runtime (its parser pulls
 * node:crypto), only its types.
 *
 *  - lhc:  hand-authored flagship (rich perspectives → perspective diff).
 *  - eggs: generated by the pipeline from a real source (matches + adversarial challenges).
 */
export const lhcBundle = lhcJson as unknown as Bundle;
export const eggsBundle = eggsJson as unknown as Bundle;
export const covidBundle = covidJson as unknown as Bundle;

export const bundles: Record<string, { label: string; bundle: Bundle }> = {
  lhc: { label: "LHC black holes", bundle: lhcBundle },
  covid: { label: "COVID origins", bundle: covidBundle },
  eggs: { label: "Eggs & heart health", bundle: eggsBundle },
};

/** A second, independently-authored same-case bundle available to merge (the compounding demo). */
export const mergePairs: Record<string, { label: string; bundle: Bundle }> = {
  lhc: { label: "investigator B — 2024 neutron-star re-derivation", bundle: lhcAddendumJson as unknown as Bundle },
};
